services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    
  db:
    container_name: db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=F8C894659B278EDAB74AA232412D1
      - MONGO_INITDB_DATABASE=helpers
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
