version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - helper-nsql

  helper-nsql:
    container_name : helper-nsql
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - helper-data:/data/db
    ports:
      - "3001:27017"

volumes:
  helper-data: